import doctor_nursing_assistant
import doctor_notas_auxiliar
import doctor_signos_vitales
import doctor_attentions_co_inherit
import doctor_patient_inherit
import doctor_nursing_configuracion
import doctor_attention_odontologia